apiVersion: v2
name: hive-monitor
description: Proxy/Otel/Prometheus Stack

type: application
appVersion: 0.1.1
version: 0.1.0

dependencies:
  - name: prometheus
    repository: https://prometheus-community.github.io/helm-charts
    version: 25.30.1
  - name: opentelemetry-collector
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    version: 0.114.0
  - name: common
    version: 2.23.0
    repository: oci://docker.io/bitnamicharts
